PREFIX qab: <http://purl.com/qado/ontology.ttl#>

SELECT ?benchmark (COUNT(?question) AS ?questions)
{
    ?question a qab:Question ;
        qab:isElementOf ?benchmark .
} GROUP BY ?benchmark HAVING (?questions >= 10) ORDER BY ?benchmark
